# Generated by Django 4.2.11 on 2024-09-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiveAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=254, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/', verbose_name='Изображение')),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('end_datetime', models.DateTimeField(verbose_name='Время завершения розыгрыша')),
                ('winners_count', models.IntegerField(verbose_name='Количество призовых мест')),
                ('is_referral_system', models.BooleanField(default=False, verbose_name='Реферальная система')),
                ('referral_invites_count', models.IntegerField(blank=True, null=True, verbose_name='Количество приглашений')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=128, unique=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('number_ticket', models.IntegerField(verbose_name='Номер тикета')),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.giveaway', verbose_name='Розыгрыш')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.telegramuser', verbose_name='Участник')),
            ],
        ),
    ]
