# Generated by Django 4.2.11 on 2024-09-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='referral_invites_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество приглашений для нового билета'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
