# Generated by Django 4.2.11 on 2024-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='jwt_token',
            field=models.CharField(blank=models.CharField(blank=True, max_length=255, null=True, verbose_name='телеграм Username'), max_length=1024, null=True, verbose_name='JWT токен lotoclub'),
        ),
    ]
