# Generated by Django 4.2.11 on 2024-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_telegramuser_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_ticket',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер тикета'),
        ),
    ]
