# Generated by Django 4.2.11 on 2024-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_ticket_create_date_alter_ticket_number_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_winner',
            field=models.BooleanField(default=False, verbose_name='Победил'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
