# Generated by Django 4.2.11 on 2024-11-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_ticket_is_winner_ticket_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='logs',
            field=models.JSONField(default=list),
        ),
    ]
