# Generated by Django 4.2.11 on 2024-11-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_ticket_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='logs',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='logs',
            field=models.JSONField(default=list),
        ),
    ]
