# Generated by Django 4.2.11 on 2024-11-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_ticket_logs_giveaway_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения розыгрыша'),
        ),
    ]
