# Generated by Django 4.2.11 on 2024-12-08 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_giveaway_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=256, verbose_name='Название канала')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('chat_id', models.BigIntegerField(verbose_name='ID канала')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Привязал')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Привязанные каналы',
            },
        ),
    ]
