# Generated by Django 4.2.11 on 2024-12-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_giveaway_image_alter_giveaway_logs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.telegramchannel', verbose_name='Канал'),
        ),
    ]
