# Generated by Django 4.2.11 on 2024-12-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_giveaway_chat_id_giveaway_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='show_media_above_text',
            field=models.BooleanField(default=False, verbose_name='Показывать изображение перед текстом'),
        ),
    ]
