# Generated by Django 4.2.11 on 2024-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_giveaway_show_media_above_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Изображение'),
        ),
    ]
