# Generated by Django 4.2.11 on 2024-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_giveaway_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения в канале'),
        ),
    ]
